const actionTypes = {
  GET_EXCHANGE_RATES_REQUEST: 'GET_EXCHANGE_RATES_REQUEST',
  GET_EXCHANGE_RATES_SUCCESS: 'GET_EXCHANGE_RATES_SUCCESS',
  GET_EXCHANGE_RATES_FAILURE: 'GET_EXCHANGE_RATES_FAILURE',
}

export default actionTypes
